"""Synthetic case generation, following the six-step recipe in the brief.

    seed from real structure -> generate -> self-critique -> hard negatives
    -> PHI and duplicate screening -> clinician spot-check

Five of those six are here. The sixth is a person, and ``review_sample`` picks
the batch for them rather than pretending to be them.

The quality gate, restated because it is the part most easily lost
--------------------------------------------------------------------
Synthetic cases are for coverage, class balance and stress-testing. They are
never the basis of a headline metric. That is not a stylistic preference: a
case generated by a model, from a knowledge base, and then used to score a
system reasoning over that same knowledge base measures self-consistency and
reports it as accuracy.

``SyntheticCase.to_case()`` therefore stamps ``synthetic-`` into the case id,
so a synthetic case entering an evaluation set is visible in every per-case
table rather than resting on someone having remembered.

On the honesty of each step
---------------------------
Step 1 seeds from the knowledge base's own vocabulary and confusable pairs, so
generated cases stay inside the concept space the system reasons over. That is
a real constraint and also a limit: cases seeded this way cannot surprise the
system with a finding it has never heard of, which is one of the things real
patients do.

Step 5's PHI screen is regular expressions. It catches structured identifiers
-- dates, phone numbers, record numbers, postcodes -- and it does not catch a
name in running prose. A real de-identification pass needs a clinical NER
model (scispacy, Presidio); this is a tripwire, not that pass, and it is
labelled as one so nobody mistakes a clean report for a clean corpus.
"""

from __future__ import annotations

import json
import random
import re
from dataclasses import dataclass, field
from typing import Any

from .environment import Case
from .knowledge import InMemoryKnowledgeBase

# Structured identifiers only. Names in prose are out of reach of a regex, and
# claiming otherwise would be worse than not screening at all.
_PHI_PATTERNS: tuple[tuple[str, str], ...] = (
    ("date", r"\b\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b"),
    ("long number", r"\b\d{7,}\b"),
    ("phone", r"\b(?:\+?\d{1,3}[ -]?)?\(?\d{3}\)?[ -]?\d{3}[ -]?\d{4}\b"),
    ("email", r"\b[\w.+-]+@[\w-]+\.[\w.]+\b"),
    ("record number", r"\b(?:MRN|NHS|SSN)[:\s#]*[\w-]+\b"),
    ("postcode", r"\b[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}\b"),
)

_SYSTEM = """You write structured clinical vignettes for testing a diagnostic \
reasoning system. They are teaching fictions, not records of real patients.

Rules:
- Use ONLY findings from the provided vocabulary. Do not invent findings.
- Include no names, dates, places, or identifiers of any kind.
- The gold diagnosis must be the single best explanation of the findings.
- Respond with JSON only, no prose and no markdown fences:
  {"cases": [{"narrative": "...", "present": ["..."], "absent": ["..."], \
"diagnosis": "...", "reasoning": "..."}]}"""

_CRITIQUE_SYSTEM = """You check clinical vignettes for internal consistency. \
You are looking for combinations that could not occur together, findings that \
contradict the stated diagnosis, and vignettes whose findings point more \
clearly at some other diagnosis than the one given.

Respond with JSON only:
  {"consistent": true|false, "problem": "..."}"""


@dataclass(frozen=True)
class SyntheticCase:
    """A generated vignette, with everything needed to audit it later."""

    case_id: str
    narrative: str
    present: tuple[str, ...]
    absent: tuple[str, ...]
    diagnosis: str
    reasoning: str
    generator: str = ""
    critique: str = ""
    accepted: bool = True

    def to_case(self, vocabulary: frozenset[str] = frozenset()) -> Case:
        features = {c: True for c in self.present}
        features.update({c: False for c in self.absent})
        return Case(
            # The prefix is load-bearing: it makes a synthetic case visible in
            # any per-case output, so one reaching a headline metric is caught
            # by reading the table rather than by remembering.
            case_id=f"synthetic-{self.case_id}",
            presenting_complaint=self.narrative,
            diagnosis=self.diagnosis,
            features=features,
            initial_findings=self.present[:2],
            vocabulary=vocabulary,
        )


def confusable_pairs(
    kb: InMemoryKnowledgeBase, limit: int = 5
) -> tuple[tuple[str, str, float], ...]:
    """Disease pairs whose likelihood profiles are hardest to tell apart.

    The brief asks for near-miss cases -- "two causes that look alike" -- and
    which two those are is measurable rather than a matter of opinion. Distance
    is the mean absolute difference in P(finding | disease) across the *union*
    of the two feature sets, backing off to the knowledge-base marginal where
    an entry does not characterise a feature.

    Comparing over the intersection instead is the obvious implementation and
    is wrong in a way worth recording: a thinly-described disease shares few
    features with anything, those few tend to be the generic ones every entry
    scores similarly, and it therefore looks confusable with everything. On the
    fixture set that ranked the two sparsest entries into every top pair. The
    union with marginal backoff is the same correction ``DiseaseEntry.
    likelihood`` already applies for the same reason -- an absence of
    description is not evidence of similarity.
    """
    entries = kb.diseases()
    scored: list[tuple[str, str, float]] = []
    for index, first in enumerate(entries):
        for second in entries[index + 1 :]:
            union = set(first.features) | set(second.features)
            if not union:
                continue
            distance = sum(
                abs(
                    first.features.get(c, kb.background(c))
                    - second.features.get(c, kb.background(c))
                )
                for c in union
            ) / len(union)
            scored.append((first.label, second.label, distance))
    scored.sort(key=lambda row: row[2])
    return tuple(scored[:limit])


@dataclass
class CaseGenerator:
    """Steps 1-4: seed, generate, critique, and target the near misses."""

    llm: Any
    kb: InMemoryKnowledgeBase
    seed: int = 0
    # Every call that produced no usable output and why. A run that generates
    # nothing should be able to say whether the model refused, the response
    # could not be parsed, or the network failed -- three very different
    # problems that an empty list on its own cannot distinguish.
    failures: list[str] = field(default_factory=list)
    _rng: random.Random = field(init=False, repr=False)

    def __post_init__(self) -> None:
        self._rng = random.Random(self.seed)

    def _vocabulary(self) -> list[str]:
        return sorted({c for e in self.kb.diseases() for c in e.features})

    def generate(
        self, diagnosis: str, count: int = 3, confusable_with: str | None = None
    ) -> list[SyntheticCase]:
        """Ask for ``count`` vignettes of one diagnosis.

        ``confusable_with`` asks for near misses: cases that genuinely are
        ``diagnosis`` but present in a way that suggests the other. Those are
        the cases the evidence weighting and the abstention gate exist for, and
        a corpus of typical presentations tests neither.
        """
        entry = self.kb.get(diagnosis)
        if entry is None:
            raise KeyError(f"{diagnosis!r} is not in the knowledge base")

        typical = sorted(
            (c for c, p in entry.features.items() if p >= 0.6), key=str
        )
        atypical = sorted(
            (c for c, p in entry.features.items() if p <= 0.2), key=str
        )
        prompt = (
            f"Write {count} vignettes whose gold diagnosis is {diagnosis}.\n\n"
            f"Findings typical of it: {', '.join(typical) or 'none recorded'}\n"
            f"Findings atypical of it: {', '.join(atypical) or 'none recorded'}\n\n"
            f"Vocabulary (use only these):\n{', '.join(self._vocabulary())}"
        )
        if confusable_with:
            prompt += (
                f"\n\nMake these near misses: the true diagnosis is "
                f"{diagnosis}, but each vignette should superficially suggest "
                f"{confusable_with}. The diagnosis field stays {diagnosis}."
            )

        try:
            raw = self.llm.complete(prompt, system=_SYSTEM)
            payload = _parse_json(raw)
        except Exception as exc:
            # Recorded, not swallowed. Returning [] alone makes a model that
            # answered fine but formatted its answer unexpectedly look
            # identical to one that refused, and the batch report then says
            # "generated 0" with nothing to explain it.
            self.failures.append(f"{diagnosis}: {type(exc).__name__}: {exc}")
            return []

        out: list[SyntheticCase] = []
        allowed = set(self._vocabulary())
        for index, item in enumerate(payload.get("cases", [])):
            present = tuple(c for c in item.get("present", []) if c in allowed)
            absent = tuple(c for c in item.get("absent", []) if c in allowed)
            if not present:
                continue
            out.append(
                SyntheticCase(
                    case_id=f"{diagnosis}-{self.seed}-{index:03d}",
                    narrative=str(item.get("narrative", "")).strip(),
                    present=present,
                    absent=absent,
                    diagnosis=diagnosis,
                    reasoning=str(item.get("reasoning", "")).strip(),
                    generator=type(self.llm).__name__,
                )
            )
        return out

    def critique(self, case: SyntheticCase) -> SyntheticCase:
        """Step 3: a second pass that can reject its own generation.

        Separate call rather than a "check your work" instruction appended to
        the first: a model asked to produce and validate in one turn tends to
        validate what it produced.
        """
        prompt = (
            f"Vignette: {case.narrative}\n"
            f"Present: {', '.join(case.present)}\n"
            f"Absent: {', '.join(case.absent)}\n"
            f"Stated diagnosis: {case.diagnosis}\n"
            f"Stated reasoning: {case.reasoning}"
        )
        try:
            payload = _parse_json(self.llm.complete(prompt, system=_CRITIQUE_SYSTEM))
        except Exception as exc:
            # An unusable critique must not silently pass the case. Reject and
            # say why, so the batch statistics show the checker failing rather
            # than the corpus looking clean.
            self.failures.append(f"critique {case.case_id}: {type(exc).__name__}: {exc}")
            return _replace(case, accepted=False, critique="critique unavailable")
        consistent = bool(payload.get("consistent", False))
        return _replace(
            case,
            accepted=consistent,
            critique=str(payload.get("problem", "")).strip(),
        )


def phi_scan(text: str) -> tuple[tuple[str, str], ...]:
    """Structured identifiers found in ``text``. See the module docstring.

    Empty output means no *pattern* matched, not that the text is free of
    identifying information.
    """
    hits: list[tuple[str, str]] = []
    for name, pattern in _PHI_PATTERNS:
        for match in re.finditer(pattern, text, flags=re.IGNORECASE):
            hits.append((name, match.group(0)))
    return tuple(hits)


def _shingles(text: str, size: int = 5) -> set[str]:
    words = re.findall(r"\w+", text.lower())
    if len(words) < size:
        return {" ".join(words)} if words else set()
    return {" ".join(words[i : i + size]) for i in range(len(words) - size + 1)}


def near_duplicates(
    cases: list[SyntheticCase], threshold: float = 0.5
) -> tuple[tuple[str, str, float], ...]:
    """Pairs whose narratives overlap above ``threshold`` (Jaccard on 5-grams).

    Generated corpora repeat themselves, and duplicates inflate a case count
    without adding coverage -- which is the one thing synthetic data is for.
    """
    grams = {c.case_id: _shingles(c.narrative) for c in cases}
    flagged: list[tuple[str, str, float]] = []
    for index, first in enumerate(cases):
        for second in cases[index + 1 :]:
            a, b = grams[first.case_id], grams[second.case_id]
            if not a or not b:
                continue
            overlap = len(a & b) / len(a | b)
            if overlap >= threshold:
                flagged.append((first.case_id, second.case_id, overlap))
    flagged.sort(key=lambda row: -row[2])
    return tuple(flagged)


def screen(
    cases: list[SyntheticCase], duplicate_threshold: float = 0.5
) -> tuple[list[SyntheticCase], dict[str, Any]]:
    """Step 5: drop cases that fail PHI or duplicate screening.

    Returns the survivors and a report. The report is the deliverable as much
    as the corpus is -- "we generated 200 cases" says nothing without "and
    discarded 34, for these reasons".
    """
    duplicate_ids = {second for _, second, _ in near_duplicates(cases, duplicate_threshold)}
    kept: list[SyntheticCase] = []
    phi_flagged: list[tuple[str, tuple[tuple[str, str], ...]]] = []

    for case in cases:
        hits = phi_scan(f"{case.narrative} {case.reasoning}")
        if hits:
            phi_flagged.append((case.case_id, hits))
            continue
        if case.case_id in duplicate_ids:
            continue
        if not case.accepted:
            continue
        kept.append(case)

    return kept, {
        "generated": len(cases),
        "kept": len(kept),
        "rejected_by_critique": sum(1 for c in cases if not c.accepted),
        "rejected_as_duplicate": len(duplicate_ids),
        "rejected_for_phi": len(phi_flagged),
        "phi_detail": phi_flagged,
    }


def review_sample(
    cases: list[SyntheticCase], size: int = 10, seed: int = 0
) -> list[SyntheticCase]:
    """Step 6: the batch a clinician should spot-check.

    Random rather than worst-first. Reviewing the cases the pipeline already
    doubts measures the checker, not the corpus, and the question this sample
    answers is whether the cases that *passed* are any good.
    """
    rng = random.Random(seed)
    return rng.sample(cases, min(size, len(cases)))


def _parse_json(raw: str) -> dict:
    """Pull a JSON object out of a model response.

    The system prompt asks for bare JSON and no fences. Models comply
    unevenly, and the ways they do not are predictable: a fenced block, a
    preamble sentence before the fence, a closing offer after the object.
    Handling only the shapes that start at character zero looks like it
    works, because the first model tried happened to produce one of them.

    Deliberately tolerant of surrounding prose and not of malformed JSON: a
    response this cannot read raises, and ``generate``/``critique`` treat
    that as the model failing rather than as an empty batch.
    """
    text = raw.strip()

    fenced = re.search(r"```(?:json)?\s*(.+?)\s*```", text, re.DOTALL)
    if fenced:
        text = fenced.group(1).strip()

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Prose on either side of a bare object: take the outermost braces.
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end <= start:
        raise ValueError(f"no JSON object found in model response: {text[:120]!r}")
    return json.loads(text[start : end + 1])


def _replace(case: SyntheticCase, **changes) -> SyntheticCase:
    import dataclasses

    return dataclasses.replace(case, **changes)


__all__ = [
    "CaseGenerator",
    "SyntheticCase",
    "confusable_pairs",
    "near_duplicates",
    "phi_scan",
    "review_sample",
    "screen",
]
